### ISSUE TITLE
Indique para quem você ama

### ISSUE THREAD

**Issue by jonatas** [inventto/tambo#10]
# Indique e receba cupons

O amigo cadastrado receberá um cupom de 25,00, quem indicar também ganhará um cupom de 25,00.
# Por e-mail

Uma caixa para colocar os e-mails e poder adicionar mais  menus para colocar mais e-mails
# Pelo facebook
- publicando
- indicando para os amigos amigos 
# Por link

Cada usuário terá uma url como: www.tambo.com.br/convide/nome.de.quem.envia.o.convite

**Comment by fagneradler** [comment]
o esquema de logar via facebook vai rolar nesta etapa?
