### ISSUE TITLE
Galeria dos artistas

### ISSUE THREAD

**Issue by jonatas** [inventto/tambo#11]
# Galeria dos Artistas
- Exibe uma lista com os artistas cadastrados
- Quando clica no artista vai para o perfil do artista
- Artistas ( com área de cadastro )
  
  Ideia: No cabeçalho da galeria pode trazer um banner com o artista da semana ou algum artista em destaque.

Nos detalhes do perfil do artista também podem haver:
- Foto do artista
- técnicas utilizadas

**Comment by fagneradler** [comment]
Nas Obras também podem ter as técnicas utilizadas naquela obra. Vamos tentar aproximar ao máximo, o cliente do processo do produto. se der ja da pra deixar preparado pra vídeo, e colocarmos vídeos para as obras mais impressionantes a principio, depois claro no shoping teremos que explorar isso com APPs e incentivos ao artista de qq lugar do brasil poder de N formas expor sua obra. os mais complicados deixamos para o passo dois do projeto.
