### ISSUE TITLE
crop images

### ISSUE THREAD

**Issue by jonatas** [inventto/tambo#15]
permitir cortar imagens dos produtos.

**Comment by lucascardoso** [comment]
https://github.com/veracross/easy_image

**Comment by jonatas** [comment]
legal Lucas. vamos ver se usamos esta ferramenta.

On Fri, Sep 5, 2014 at 10:43 AM, Lucas Cardoso de Araujo <
notifications@github.com> wrote:

> https://github.com/veracross/easy_image
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/inventto/tambo/issues/15#issuecomment-54626107.

## 

atenciosamente,

Jônatas Davi Paganini.

## 

[ _ideia.me http://ideia.me *_eu\* _invent.to http://invent.to/_ ]
46 9911 7879
