### ISSUE TITLE
Autenticação do usuário

### ISSUE THREAD

**Issue by jonatas** [inventto/tambo#2]
Autenticação do usuário será necessário para o administrador, assim como para o artista interagir com a Tambo.

Deve ter as seguintes permissões de usuário:
- Administrador
- Artista
- Cliente

O usuário poderá fazer o login e o administrador dará permissão para o usuário.

**Comment by fagneradler** [comment]
vou comentar algo que vi hoje:

des de ontem somos parceiros do http://www.meliuz.com.br/ eles oferecem cupons de desconto pra uma lista de clientes, e hoje recebi em quanto usuário uma extensão para o crome, que detecta se a loja que estou visitando é parceira da meliuz e aparece na tela cupons de desconto daquela loja. 

Achei interessante o fato de uma extenção saber o site que estou navegando e estourar um pop-up na minha cara
