### ISSUE TITLE
Coleções de obras

### ISSUE THREAD

**Issue by jonatas** [inventto/tambo#4]
As coleções agrupam as obras e deveram ser criadas previamente ao cadastro das obras.

Cada obra pertence a apenas UMA coleção.

A coleção será também um fator decisivo sobre o leiaute da página. Quando o usuário estiver navegando em uma determinada coleção terá o leiaute com o tema para coleção.

As coleções iniciais são:
- Pin up girls
- Rock
- ?

**Comment by jonatas** [comment]
@fagneradler por favor adicione as outras coleções iniciais.

**Comment by fagneradler** [comment]
Uma obra pode ser de várias coleções

fagner_moveis

De: Jônatas Davi Paganini [mailto:notifications@github.com] 
Enviada em: quinta-feira, 24 de julho de 2014 10:30
Para: inventto/tambo
Assunto: [tambo] Coleções de obras (#4)

As coleções agrupam as obras e deveram ser criadas previamente ao cadastro das obras.

Cada obra pertence a apenas UMA coleção.

A coleção será também um fator decisivo sobre o leiaute da página. Quando o usuário estiver navegando em uma determinada coleção terá o leiaute com o tema para coleção.

As coleções iniciais são:
-   Pin up girls
-   Rock
-   ?

**Comment by fagneradler** [comment]
Estou trabalhando nelas ainda, conforma a disposição de artes que estou montando por conta própria, para as coleções existentes já terem conteúdo inicial também.

Conforme tiver definido, vou apssando

fagner_moveis

De: Jônatas Davi Paganini [mailto:notifications@github.com] 
Enviada em: quinta-feira, 24 de julho de 2014 10:30
Para: inventto/tambo
Cc: Fagner Seffrin Adler
Assunto: Re: [tambo] Coleções de obras (#4)

@fagneradler https://github.com/fagneradler  por favor adicione as outras coleções iniciais.
