### ISSUE TITLE
Banners de promoção

### ISSUE THREAD

**Issue by jonatas** [inventto/tambo#5]
Os banners de promoção deverão trazer os seguintes campos:
- Promoção valida entre: data inicial e final.
- % de desconto
- Mensagem da promoção
- Obras que estão em promoção

**Comment by jonatas** [comment]
@fagneradler acha necessário também termos uma imagem do banner?

**Comment by fagneradler** [comment]
não entendi a pergunta jonatas.. o banner que propuz no layout é parte imagem parte textual. aquelas bolinhas são PNGs com fundo transparente seguido de um texto naquela fonte. são duas bolinhas por vez e mais um lugar para colocar algo do tipo 12x sem juros do paypal, que também pode ser um PNG com transparencia,

quem sabe cada uma destas 3 partes do banner possam ter prazos e programação para trocar para uma próxima a partir de tal horario, como se fosse um banco de dados de banners. 

cada uma destas partes ao clicar aponta para um produto direto a princípio. vamos chamar de obra, apenas o que for de um artista, por exemplo, uma tela, uma escultura, são obras, revendidas pela tambo, um produto como o caso de um bistro com 2 banquetas( um Conjunto ou KIT ).

mas me deu uma ideia um banner pode por sí próprio ao ser clicado mudar os produtos da capa do site, sendo eles os referentes ao produto. algo assim?
