### ISSUE TITLE
Perfil do artista

### ISSUE THREAD

**Issue by jonatas** [inventto/tambo#6]
O artista também terá um perfil público com seus dados e acesso as obras do mesmo.

No perfil deve ter as seguintes informações:
- Nome
- Url curta de acesso ao profile publico do artista
- Cidade
- Biografia
- Foto do perfil
- Foto de capa
- Obras
- Produzindo para tambo desde a data..
- Foto do artista
- técnicas utilizadas

**Comment by jonatas** [comment]
@fagneradler  vamos pensar nos outros pontos a explorar no futuro:
- preço médio das artes
- faturamento médio do artista
- número de artes vendidas
- encomendar arte deste artista

**Comment by fagneradler** [comment]
"produzindo para a Tambo" melhor: "Com a Tambo desde:" data
sobre o futuro, sim! ótimo, "encomendar" é muito interessante. e os valores médios sempre colaboram ao relacionamento pautado em coisas bem palpáveis. o achismo leva as parcerias a falência.
