### ISSUE TITLE
Atendimento super

### ISSUE THREAD

**Issue by jonatas** [inventto/tambo#9]
- Formulário simples para contato
- Verificar possibilidade de enviar um SMS para o telefone do administrador (@fagneradler)
-  Dados da empresa 
-  Chat

**Comment by jonatas** [comment]
@fagneradler temos um parceiro aqui da empresa que trabalha com pacotes de SMS estamos para pegar uns pacotes então podemos implantar sim.

**Comment by fagneradler** [comment]
ótimo, a ideia é não depender de um ponto fixo ( escritório ) para atender bem o Cliente, sendo que nesta etapa devo estar muito pra la e pra cá com os artistas, e não quero precisar contar com uma secretária por exemplo no escritório, o CRP é integrado com a Nuvemshop então os pedidos ali criados, envio em uma impressora cloud que ja está instalada e testada na fábrica, para impressão dos pedidos e notas fiscais.

o SMS é bom pq mesmo sem sinal no celular, em minutos recebo a pergunta do cliente e ja respondo mesmo sem wifi.
